#! /bin/sh
# /etc/init.d/moisured     
 
### BEGIN INIT INFO
# Provides:          detector-init
# Required-Start:    $all
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script de ejemplo de arranque automático
# Description:       Script para arrancar el monitoreo de ambiente
### END INIT INFO
 
 
# Dependiendo de los parámetros que se le pasen al programa se usa una opción u otra
case "$1" in
  start)
    echo "Arrancando Sensor de Humedad"
    # Aquí hay que poner el programa que quieras arrancar automáticamente
    /usr/bin/python /home/pi/proyecto2/ProyectoFinalSIM/codigo.py
    ;;
  stop)
    echo "Deteniendo Sensor de Humedad"
 
    ;;
  *)
    echo "Modo de uso: /etc/init.d/moisured {start|stop}"
    exit 1
    ;;
esac
 
exit 0
